(91) Show optional fields and validation errors
LBHackney-IT/maintain-my-home pull request #19
Opened 2017-10-04 14:31 UTC by leeky

- Forms now indicate when fields are optional rather than when they are required
 - The 'describe unknown repair' and 'contact details' forms have required fields, so now have form objects to perform validation
 - Validation prevents incomplete forms being submitted
 - Validation errors are in the GOVUK style
 -  Optional fields need to have labels

NB: GOVUK style suggested having a series of links to the invalid fields at the top of the page. This is quite hard to do because it requires some additional ARIA attributes on the form and error fields. I've therefore omitted this for now, which feels fine since we're avoiding too many questions per page.

2017-10-04 15:53 UTC, dgmstuart commented
The validations on the first page don't seem to be styled (yes, I had to force the submit button to be displayed using the inspector):
<img width="663" alt="screen shot 2017-10-04 at 16 52 14" src="https://user-images.githubusercontent.com/393167/31185670-7da588c0-a924-11e7-9a29-43e6a2f0bd06.png">

2017-10-04 15:55 UTC, dgmstuart commented
Ditto the Address selection page, which also jumps back to the address search page instead of re-rendering the address selection list:

<img width="572" alt="screen shot 2017-10-04 at 16 54 37" src="https://user-images.githubusercontent.com/393167/31185793-c90fa232-a924-11e7-83d6-40992c4c3a74.png">

2017-10-04 15:57 UTC, dgmstuart requested changes
Generally looks great - the errors on individual fields look really nice.

The main thing missing is specs which test the forms being submitted successfully.

2017-10-04 15:57 UTC, dgmstuart commented on spec/models/contact_details_form_spec.rb
> +    it '.full_name' do
I guess 'it validates presence of full name' is more descriptive but more verbose?
This is fine for now, but at some point we're going to need additional validations - e.g. field length

2017-10-04 15:57 UTC, dgmstuart commented on spec/models/contact_details_form_spec.rb
> +  describe 'validations' do
Do we need a spec that shows that this is valid when all fields are present? I think currently this would pass if `valid?` was always false.

2017-10-04 15:57 UTC, dgmstuart commented on spec/models/contact_details_form_spec.rb
> +    it '.callback_time' do
Would there be value in demonstrating that this form is valid when only one checkbox is checked?

2017-10-04 15:57 UTC, dgmstuart commented on config/initializers/simple_form.rb
> +  config.label_text = ->(label, required, _explicit_label) { "#{label} #{required}" }
Are we able to rename this parameter to `optional`? Would that make any sense?

2017-10-04 15:57 UTC, dgmstuart commented on config/initializers/simple_form.rb
> +  config.label_text = ->(label, required, _explicit_label) { "#{label} #{required}" }
Also: this will result in a space after the label for required fields. Probably no big deal?
It made sense in the blog post because they were marking both required and optional fields.

2017-10-04 15:57 UTC, dgmstuart commented on spec/features/users_cannot_submit_incomplete_forms_spec.rb
> +    end
Do we now need further steps in this spec to show that after these validation errors we can go on to successfully submit a form?

2017-10-04 15:57 UTC, dgmstuart commented on app/controllers/contact_details_controller.rb
> +    @selected_answers = selected_answer_store.selected_answers['address']
Do we need @selected_answers in the happy path case?
I'm never quite sure if it's worth making the distinction in this sort of situation.

2017-10-04 16:10 UTC, leeky commented on app/controllers/contact_details_controller.rb
> +    @selected_answers = selected_answer_store.selected_answers['address']
I did this so that the `index` and `submit` methods were similar shaped, rather than having the `SelectedAnswerStore` being in the conditional.

2017-10-09 14:10 UTC, leeky commented on spec/models/contact_details_form_spec.rb
> +  describe 'validations' do
:+1: Added

2017-10-09 14:16 UTC, leeky commented on config/initializers/simple_form.rb
> +  config.label_text = ->(label, required, _explicit_label) { "#{label} #{required}" }
I think the default behaviour (prefixing an asterisk to required fields) also adds an extra space. I've fixed this in this instance however.

Also, same with renaming parameter to `optional`.

2017-10-09 15:41 UTC, dgmstuart commented on app/controllers/addresses_controller.rb
> +    @form = AddressForm.new(address_form_params)
Nice - I like this :)

2017-10-09 15:43 UTC, dgmstuart commented on app/controllers/addresses_controller.rb
> +  def address_form_params
Ah this tidy up feels good

2017-10-09 15:47 UTC, dgmstuart approved these changes
Looks great to me 👍

2017-10-09 15:47 UTC, merged