(153) Start page content
LBHackney-IT/maintain-my-home pull request #30
Opened 2017-10-18 09:32 UTC by leeky

<img width="846" alt="start-page-new" src="https://user-images.githubusercontent.com/3166/31711326-a67b6b5e-b3ef-11e7-97f6-6493551b2734.png">

2017-10-18 10:36 UTC, dgmstuart requested changes
I hate to be that guy, but does this maybe "need more whitespace"? On the example on gov.uk the page is broken up into 3 distinct sections:
https://www.gov.uk/service-manual/design/start-pages

At the moment the start page feels like all one block, which might feel intimidating.

Perhaps some more space between title, "what this is" and "before you start" would help with that?

Also in the "before you start" section the spacing between the title and the two paras feels odd to me. In the Gov.uk example these are evenly spaced.

2017-10-19 10:18 UTC, leeky commented
I've given the styling a good kick - increasing whitespace, using the correct font etc, and added some commits to this branch:

![report-a-repair](https://user-images.githubusercontent.com/3166/31766299-14fd51a8-b4bf-11e7-90e9-beedbf14f335.png)

2017-10-19 10:32 UTC, leeky commented
@dgmstuart Should be ready for another look.

2017-10-23 09:32 UTC, dgmstuart approved these changes

2017-10-23 09:33 UTC, merged